name: Test actions/build

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# NOTE: Fixes "Error: Resource not accessible by integration"
permissions:
  contents: read
  security-events: write

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/build
        with:
          working-directory: assets/docker/node
          dockerfile: Dockerfile
          target: final

  matrix:
    needs: default
    if: always()
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        dockerfile:
          - Dockerfile
          - Dockerfile.next

        target:
          # dev
          - tested

          # release
          - release

        # Already tested in default
        exclude:
          - dockerfile: Dockerfile
            target: release

        include:
          - dockerfile: Dockerfile
            image_tag_suffix: latest

          - dockerfile: Dockerfile.next
            image_tag_suffix: next

    runs-on: ubuntu-latest
    name: "${{ matrix.dockerfile }}: ${{ matrix.target }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/build
        with:
          working-directory: assets/docker/node
          dockerfile: ${{ matrix.dockerfile }}
          target: ${{ matrix.target }}
          image_tag_suffix: ${{ matrix.image_tag_suffix }}
